services:
  # Frontend Next.js service
  - type: web
    name: clem-todo-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
    autoDeploy: true

  # Backend FastAPI service
  - type: web
    name: clem-todo-backend
    env: python
    plan: free
    buildCommand: cd api && pip install -r requirements.txt
    startCommand: cd api && gunicorn server:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 30
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true 