services:
  # Frontend Next.js service
  - type: web
    name: clem-todo-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: true

  # Backend FastAPI service
  - type: web
    name: clem-todo-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://clem-todo-frontend.onrender.com
      - key: VERIFY_TOKEN
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PUSHOVER_API_TOKEN
        sync: false
      - key: PUSHOVER_USER_KEY
        sync: false
      - key: RECIPIENT_USER_KEY
        sync: false
    autoDeploy: true 