jobs:
  # Cron job to check for reminders
  - type: cron
    name: check-reminders
    schedule: "0 * * * *"  # Run on the hour, every hour
    command: curl -X POST -H "Authorization: Bearer ${VERIFY_TOKEN}" https://clem-todo-backend.onrender.com/api/check-reminders
    envVars:
      - key: VERIFY_TOKEN
        sync: false  # This will be set in the Render dashboard
    dependsOn:
      - clem-todo-backend 